FROM python:3.9-bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    tcpdump \
    openjdk-17-jre-headless \
    libpcap-dev \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && which tcpdump \
    && tcpdump --version

RUN pip install --no-cache-dir \
    flask \
    requests \
    kubernetes \
    cicflowmeter \
    scapy

WORKDIR /app

COPY controller.py .

ENV PYTHONUNBUFFERED=1

CMD ["python3", "-u", "controller.py"]